### ISSUE TITLE
+ is shown as %2B and space as %20

### ISSUE THREAD

**Issue by 532910** [Chooloo/call_manage#50]
![image](https://user-images.githubusercontent.com/14617699/78462799-40312000-76de-11ea-8ed6-79309d21ab30.png)

![image](https://user-images.githubusercontent.com/14617699/78462825-838b8e80-76de-11ea-91f6-a16128fcaa78.png)

Lineage os 16.0 based on android 9 OP3T

**Comment by roeiedri** [comment]
Can you elaborate more? what name is supposed to be showen?

**Comment by 532910** [comment]
Sorry what name? It must show `+` sign instead of `%2B` and space instead of `%20`.
What it's unclear here?

**Comment by 532910** [comment]
It's phone number, not a name.

**Comment by 532910** [comment]
Like `+7 999 666-13-13` but shown as `%2B7%20999%20666-13-13`

**Comment by roeiedri** [comment]
Hey are you a developer? WIll you be able to make an apk and see of the problem was solved for you? it should be

**Comment by 532910** [comment]
I believe I should be a developer to be able to compile (:
Sometimes I'm thinking about to set up android build env, but still hasn't it.
But I'm ready to test apk it you'll share it.

**Comment by 532910** [comment]
Just tested: not fixed, please reopen.
Right now it doesn't show + neither spaces at all

**Comment by 532910** [comment]
![Screenshot_20200618-084207_Koler](https://user-images.githubusercontent.com/14617699/84982550-a7883900-b13f-11ea-9f02-b38297e75d2c.png)
